spring:
  profiles:
    default: dev

mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.ddp.res.pojo
  globalConfig:
    dbConfig:
      idType: AUTO

server:
  shutdown: "graceful"
  servlet:
    register-default-servlet: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
